language: python

os:
  - linux
  - osx

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install nanomath
  - pip install flake8
# command to run tests
script:
  - python -c "import nanomath"
  - flake8 .
